USE [ONESHOP];
GO

CREATE TABLE [dbo].[Users](
	[Sequence] [BIGINT] IDENTITY(1,1) NOT NULL, -- Has to keep this incremental.
	[UserName] [VARCHAR](200) NOT NULL UNIQUE,
	[UserId] AS ('ONESHOP' + RIGHT(REPLICATE('0', 13) + CAST([Sequence] AS VARCHAR(13)), 13)) PERSISTED NOT NULL UNIQUE,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[UserName] ASC
) WITH (
	PAD_INDEX = OFF,
	STATISTICS_NORECOMPUTE = OFF,
	IGNORE_DUP_KEY = OFF,
	ALLOW_ROW_LOCKS = ON,
	ALLOW_PAGE_LOCKS = ON,
	FILLFACTOR = 90
) ON [PRIMARY]
) ON [PRIMARY]
GO