USE [ONESHOP];
GO

CREATE TABLE [dbo].[CountryMaster](
	[Sequence] [BIGINT] IDENTITY(1,1) NOT NULL,
	[Country] [VARCHAR](100) NOT NULL,
	[CountryCode] [VARCHAR](3) NOT NULL,
	[ISDCode] [VARCHAR](8) NOT NULL,
    [Flag] NVARCHAR(50) NULL,
	CONSTRAINT [PK_CountryMaster] PRIMARY KEY CLUSTERED ([Country] ASC)
	WITH (PAD_INDEX = OFF,
		STATISTICS_NORECOMPUTE = OFF,
		IGNORE_DUP_KEY = OFF,
		ALLOW_ROW_LOCKS = ON,
		ALLOW_PAGE_LOCKS = ON,
		FILLFACTOR = 90
	) ON [PRIMARY],
	CONSTRAINT [UK_CountryMaster_CountryCode] UNIQUE ([CountryCode])
) ON [PRIMARY]
GO

/***************************************************************************************************************************/
INSERT INTO [dbo].[CountryMaster] ([Country], [CountryCode], [ISDCode], [Flag]) VALUES
('Afghanistan', 'AF', '+93', N'????'),
('Albania', 'AL', '+355', N'????'),
('Algeria', 'DZ', '+213', N'????'),
('Andorra', 'AD', '+376', N'????'),
('Angola', 'AO', '+244', N'????'),
('Antigua and Barbuda', 'AG', '+1-268', N'????'),
('Argentina', 'AR', '+54', N'????'),
('Armenia', 'AM', '+374', N'????'),
('Australia', 'AU', '+61', N'????'),
('Austria', 'AT', '+43', N'????'),
('Azerbaijan', 'AZ', '+994', N'????'),
('Bahamas', 'BS', '+1-242', N'????'),
('Bahrain', 'BH', '+973', N'????'),
('Bangladesh', 'BD', '+880', N'????'),
('Barbados', 'BB', '+1-246', N'????'),
('Belarus', 'BY', '+375', N'????'),
('Belgium', 'BE', '+32', N'????'),
('Belize', 'BZ', '+501', N'????'),
('Benin', 'BJ', '+229', N'????'),
('Bhutan', 'BT', '+975', N'????'),
('Bolivia', 'BO', '+591', N'????'),
('Bosnia and Herzegovina', 'BA', '+387', N'????'),
('Botswana', 'BW', '+267', N'????'),
('Brazil', 'BR', '+55', N'????'),
('Brunei', 'BN', '+673', N'????'),
('Bulgaria', 'BG', '+359', N'????'),
('Burkina Faso', 'BF', '+226', N'????'),
('Burundi', 'BI', '+257', N'????'),
('Cambodia', 'KH', '+855', N'????'),
('Cameroon', 'CM', '+237', N'????'),
('Canada', 'CA', '+1', N'????'),
('Cape Verde', 'CV', '+238', N'????'),
('Central African Republic', 'CF', '+236', N'????'),
('Chad', 'TD', '+235', N'????'),
('Chile', 'CL', '+56', N'????'),
('China', 'CN', '+86', N'????'),
('Colombia', 'CO', '+57', N'????'),
('Comoros', 'KM', '+269', N'????'),
('Congo (Republic)', 'CG', '+242', N'????'),
('Congo (Democratic Republic)', 'CD', '+243', N'????'),
('Costa Rica', 'CR', '+506', N'????'),
('Croatia', 'HR', '+385', N'????'),
('Cuba', 'CU', '+53', N'????'),
('Cyprus', 'CY', '+357', N'????'),
('Czech Republic', 'CZ', '+420', N'????'),
('Denmark', 'DK', '+45', N'????'),
('Djibouti', 'DJ', '+253', N'????'),
('Dominica', 'DM', '+1-767', N'????'),
('Dominican Republic', 'DO', '+1-809', N'????'),
('Ecuador', 'EC', '+593', N'????'),
('Egypt', 'EG', '+20', N'????'),
('El Salvador', 'SV', '+503', N'????'),
('Equatorial Guinea', 'GQ', '+240', N'????'),
('Eritrea', 'ER', '+291', N'????'),
('Estonia', 'EE', '+372', N'????'),
('Eswatini', 'SZ', '+268', N'????'),
('Ethiopia', 'ET', '+251', N'????'),
('Fiji', 'FJ', '+679', N'????'),
('Finland', 'FI', '+358', N'????'),
('France', 'FR', '+33', N'????'),
('Gabon', 'GA', '+241', N'????'),
('Gambia', 'GM', '+220', N'????'),
('Georgia', 'GE', '+995', N'????'),
('Germany', 'DE', '+49', N'????'),
('Ghana', 'GH', '+233', N'????'),
('Greece', 'GR', '+30', N'????'),
('Grenada', 'GD', '+1-473', N'????'),
('Guatemala', 'GT', '+502', N'????'),
('Guinea', 'GN', '+224', N'????'),
('Guinea-Bissau', 'GW', '+245', N'????'),
('Guyana', 'GY', '+592', N'????'),
('Haiti', 'HT', '+509', N'????'),
('Honduras', 'HN', '+504', N'????'),
('Hungary', 'HU', '+36', N'????'),
('Iceland', 'IS', '+354', N'????'),
('India', 'IN', '+91', N'????'),
('Indonesia', 'ID', '+62', N'????'),
('Iran', 'IR', '+98', N'????'),
('Iraq', 'IQ', '+964', N'????'),
('Ireland', 'IE', '+353', N'????'),
('Israel', 'IL', '+972', N'????'),
('Italy', 'IT', '+39', N'????'),
('Jamaica', 'JM', '+1-876', N'????'),
('Japan', 'JP', '+81', N'????'),
('Jordan', 'JO', '+962', N'????'),
('Kazakhstan', 'KZ', '+7', N'????'),
('Kenya', 'KE', '+254', N'????'),
('Kiribati', 'KI', '+686', N'????'),
('Kuwait', 'KW', '+965', N'????'),
('Kyrgyzstan', 'KG', '+996', N'????'),
('Laos', 'LA', '+856', N'????'),
('Latvia', 'LV', '+371', N'????'),
('Lebanon', 'LB', '+961', N'????'),
('Lesotho', 'LS', '+266', N'????'),
('Liberia', 'LR', '+231', N'????'),
('Libya', 'LY', '+218', N'????'),
('Liechtenstein', 'LI', '+423', N'????'),
('Lithuania', 'LT', '+370', N'????'),
('Luxembourg', 'LU', '+352', N'????'),
('Madagascar', 'MG', '+261', N'????'),
('Malawi', 'MW', '+265', N'????'),
('Malaysia', 'MY', '+60', N'????'),
('Maldives', 'MV', '+960', N'????'),
('Mali', 'ML', '+223', N'????'),
('Malta', 'MT', '+356', N'????'),
('Marshall Islands', 'MH', '+692', N'????'),
('Mauritania', 'MR', '+222', N'????'),
('Mauritius', 'MU', '+230', N'????'),
('Mexico', 'MX', '+52', N'????'),
('Micronesia', 'FM', '+691', N'????'),
('Moldova', 'MD', '+373', N'????'),
('Monaco', 'MC', '+377', N'????'),
('Mongolia', 'MN', '+976', N'????'),
('Montenegro', 'ME', '+382', N'????'),
('Morocco', 'MA', '+212', N'????'),
('Mozambique', 'MZ', '+258', N'????'),
('Myanmar', 'MM', '+95', N'????'),
('Namibia', 'NA', '+264', N'????'),
('Nauru', 'NR', '+674', N'????'),
('Nepal', 'NP', '+977', N'????'),
('Netherlands', 'NL', '+31', N'????'),
('New Zealand', 'NZ', '+64', N'????'),
('Nicaragua', 'NI', '+505', N'????'),
('Niger', 'NE', '+227', N'????'),
('Nigeria', 'NG', '+234', N'????'),
('North Korea', 'KP', '+850', N'????'),
('North Macedonia', 'MK', '+389', N'????'),
('Norway', 'NO', '+47', N'????'),
('Oman', 'OM', '+968', N'????'),
('Pakistan', 'PK', '+92', N'????'),
('Palau', 'PW', '+680', N'????'),
('Palestine', 'PS', '+970', N'????'),
('Panama', 'PA', '+507', N'????'),
('Papua New Guinea', 'PG', '+675', N'????'),
('Paraguay', 'PY', '+595', N'????'),
('Peru', 'PE', '+51', N'????'),
('Philippines', 'PH', '+63', N'????'),
('Poland', 'PL', '+48', N'????'),
('Portugal', 'PT', '+351', N'????'),
('Qatar', 'QA', '+974', N'????'),
('Romania', 'RO', '+40', N'????'),
('Russia', 'RU', '+7', N'????'),
('Rwanda', 'RW', '+250', N'????'),
('Saint Kitts and Nevis', 'KN', '+1-869', N'????'),
('Saint Lucia', 'LC', '+1-758', N'????'),
('Saint Vincent and the Grenadines', 'VC', '+1-784', N'????'),
('Samoa', 'WS', '+685', N'????'),
('San Marino', 'SM', '+378', N'????'),
('Sao Tome and Principe', 'ST', '+239', N'????'),
('Saudi Arabia', 'SA', '+966', N'????'),
('Senegal', 'SN', '+221', N'????'),
('Serbia', 'RS', '+381', N'????'),
('Seychelles', 'SC', '+248', N'????'),
('Sierra Leone', 'SL', '+232', N'????'),
('Singapore', 'SG', '+65', N'????'),
('Slovakia', 'SK', '+421', N'????'),
('Slovenia', 'SI', '+386', N'????'),
('Solomon Islands', 'SB', '+677', N'????'),
('Somalia', 'SO', '+252', N'????'),
('South Africa', 'ZA', '+27', N'????'),
('South Korea', 'KR', '+82', N'????'),
('South Sudan', 'SS', '+211', N'????'),
('Spain', 'ES', '+34', N'????'),
('Sri Lanka', 'LK', '+94', N'????'),
('Sudan', 'SD', '+249', N'????'),
('Suriname', 'SR', '+597', N'????'),
('Sweden', 'SE', '+46', N'????'),
('Switzerland', 'CH', '+41', N'????'),
('Syria', 'SY', '+963', N'????'),
('Taiwan', 'TW', '+886', N'????'),
('Tajikistan', 'TJ', '+992', N'????'),
('Tanzania', 'TZ', '+255', N'????'),
('Thailand', 'TH', '+66', N'????'),
('Timor-Leste', 'TL', '+670', N'????'),
('Togo', 'TG', '+228', N'????'),
('Tonga', 'TO', '+676', N'????'),
('Trinidad and Tobago', 'TT', '+1-868', N'????'),
('Tunisia', 'TN', '+216', N'????'),
('Turkey', 'TR', '+90', N'????'),
('Turkmenistan', 'TM', '+993', N'????'),
('Tuvalu', 'TV', '+688', N'????'),
('Uganda', 'UG', '+256', N'????'),
('Ukraine', 'UA', '+380', N'????'),
('United Arab Emirates', 'AE', '+971', N'????'),
('United Kingdom', 'GB', '+44', N'????'),
('United States', 'US', '+1', N'????'),
('Uruguay', 'UY', '+598', N'????'),
('Uzbekistan', 'UZ', '+998', N'????'),
('Vanuatu', 'VU', '+678', N'????'),
('Vatican City', 'VA', '+379', N'????'),
('Venezuela', 'VE', '+58', N'????'),
('Vietnam', 'VN', '+84', N'????'),
('Yemen', 'YE', '+967', N'????'),
('Zambia', 'ZM', '+260', N'????'),
('Zimbabwe', 'ZW', '+263', N'????');