<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HotChocolate.AspNetCore" Version="16.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="OneShop.App\src\app\core\layouts\dashboard-layout\" />
    <Folder Include="OneShop.App\src\app\core\layouts\components\" />
    <Folder Include="OneShop.App\src\app\core\layouts\public-layout\" />
    <Folder Include="OneShop.App\src\app\core\services\" />
    <Folder Include="OneShop.App\src\app\features\authentication\login\" />
    <Folder Include="OneShop.App\src\app\features\authentication\vendor-register\" />
    <Folder Include="OneShop.App\src\app\features\authentication\register\" />
    <Folder Include="OneShop.App\src\app\features\company\models\" />
    <Folder Include="OneShop.App\src\app\features\company\services\" />
    <Folder Include="OneShop.App\src\app\shared\" />
    <Folder Include="OneShop.App\src\styles\themes\" />
  </ItemGroup>

</Project>
